name: Docs2

on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - feature/**

env:
  GIT_FETCH_JOBS: 8
  NET_RETRY_COUNT: 5
  DEFAULT_BUILD_VARIANT: debug,release

jobs:
  docs2:
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            container: ubuntu:24.04

    timeout-minutes: 240
    runs-on: ${{matrix.os}}
    container: ${{matrix.container}}

    steps:
      - name: Packages
        run: |
            set -xe
            pwd
            whoami
            ls -al
            apt-get update
            apt-get install -y curl sudo git wget
            git status
              || git config --system --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 3

      - name: Safe dir
        run: |
            set -xe
            pwd
            whoami
            ls -al
            git status
              || git config --system --add safe.directory "$GITHUB_WORKSPACE"

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'doc/**'

      - if: steps.changes.outputs.src == 'true'
        name: Build docs
        run: |
            set -xe
            pwd
            whoami
            ls -al
            curl  --retry-all-errors --connect-timeout 15 -sSL --retry 5 -o linuxdocs.sh https://raw.githubusercontent.com/boostorg/release-tools/refs/heads/master/build_docs/linuxdocs.sh
            chmod 755 linuxdocs.sh
            ./linuxdocs.sh --boostrelease
